import { Roboto_Condensed } from 'next/font/google';
import './globals.css';
import Providers from '@/contexts/Providers';
import NavBar from '@/components/NavBar/NavBar';

const robotoCondensed = Roboto_Condensed({ subsets: ['latin'] });

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={robotoCondensed.className}>
				<Providers>
					<NavBar />
					{children}
				</Providers>
			</body>
		</html>
	);
}
